### ISSUE TITLE
orbit-components doesn't work in NextJS: "Cannot read property 'paddingAlert' of undefined"

### ISSUE THREAD

**Issue by yassinebridi** [kiwicom/orbit-components#1071]
## Expected Behavior

Fot the orbit-components to work
## Current Behavior

it shows this error:

Cannot read property 'paddingAlert' of undefined
TypeError: Cannot read property 'paddingAlert' of undefined
    at /home/yaslix/projects/sajel/frontend/node_modules/@kiwicom/orbit-components/lib/Alert/index.js:98:538
    at flatten (/home/yaslix/projects/sajel/frontend/node_modules/styled-components/dist/styled-components.cjs.js:1292:21)
    at flatten (/home/yaslix/projects/sajel/frontend/node_modules/styled-components/dist/styled-components.cjs.js:1272:16)
    at ComponentStyle.generateAndInjectStyles (/home/yaslix/projects/sajel/frontend/node_modules/styled-components/dist/styled-components.cjs.js:1481:19)
    at StyledComponent.generateAndInjectStyles (/home/yaslix/projects/sajel/frontend/node_modules/styled-components/dist/styled-components.cjs.js:2160:36)
    at StyledComponent.renderInner (/home/yaslix/projects/sajel/frontend/node_modules/styled-components/dist/styled-components.cjs.js:2063:33)
    at ReactDOMServerRenderer.render (/home/yaslix/projects/sajel/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3412:55)
    at ReactDOMServerRenderer.read (/home/yaslix/projects/sajel/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToString (/home/yaslix/projects/sajel/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)
    at render (/home/yaslix/projects/sajel/frontend/node_modules/next-server/dist/server/render.js:86:16)
    at renderPage (/home/yaslix/projects/sajel/frontend/node_modules/next-server/dist/server/render.js:211:20)
    at Function.value (/home/yaslix/projects/sajel/frontend/.next/server/static/development/pages/_document.js:555:41)
    at Object.loadGetInitialProps (/home/yaslix/projects/sajel/frontend/node_modules/next-server/dist/lib/utils.js:42:35)
    at Object.renderToHTML (/home/yaslix/projects/sajel/frontend/node_modules/next-server/dist/server/render.js:218:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)

## Context (Environment)

NextJS: 8,
"@kiwicom/orbit-components": "^0.44.0"
"styled-components": "^4.2.0"

this is my whole dependencies if it helps:
```json
 "dependencies": {
    "@kiwicom/orbit-components": "^0.44.0",
    "apollo-boost": "^0.4.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-plugin-styled-components": "^1.10.0",
    "date-fns": "^2.0.0-alpha.7",
    "downshift": "^2.2.3",
    "graphql": "^14.3.1",
    "graphql-tag": "^2.10.1",
    "lodash.debounce": "^4.0.8",
    "next": "^8.1.0",
    "next-with-apollo": "^3.4.0",
    "nprogress": "^0.2.0",
    "prop-types": "^15.6.2",
    "react": "^16.8.6",
    "react-adopt": "^0.6.0",
    "react-apollo": "^2.5.6",
    "react-dom": "^16.8.6",
    "react-transition-group": "^2.5.0",
    "styled-components": "^4.2.0"
  },
  "devDependencies": {
    "babel-plugin-module-resolver": "^3.1.1",
    "eslint": "^5.16.0",
    "eslint-plugin-react": "^7.13.0",
    "graphql-tools": "^4.0.4"
  },
```
ps: it's works perfectly with raw react, i find the problem with just NextJS
ps2: styled-components works perfectly in my NextJS app

**Comment by filipdanisko** [comment]
We have a Next.js example setup [here](https://github.com/zeit/next.js/tree/canary/examples/with-orbit-components)

**Comment by vepor** [comment]
This seems weird. Can you check if you have installed `orbit-design-tokens` in `yarn.lock` or `package-lock.json`? `orbit-design-tokens` is direct dependency of `orbit-components` and it should work properly.

**Comment by yassinebridi** [comment]
It seems i didn't know how to set it up in the first place,
I used the example provided [_app.js](https://github.com/zeit/next.js/blob/canary/examples/with-orbit-components/pages/_app.js).
I was injecting my own custom theme rather then orbit's getTokens.
Thanks guys for helping.
